from __future__ import annotations

from typing import TYPE_CHECKING

from mongomig.cli.context import GlobalOptions, load_config, load_graph, relpath
from mongomig.errors import RevisionConflictError
from mongomig.migrations.revision import write_revision
from mongomig.schema.snapshot import snapshot_hash

if TYPE_CHECKING:
    from rich.console import Console

    from mongomig.cli.commands._schema import SchemaState
    from mongomig.config.models import LoadedConfig
    from mongomig.migrations.graph import RevisionGraph
    from mongomig.output.console import Output


def run(
    opts: GlobalOptions,
    out: Output,
    *,
    message: str,
    head: str | None,
    rev_id: str | None,
    autogenerate: bool = False,
    renames: list[str] | None = None,
) -> None:
    config = load_config(opts, out)
    graph = load_graph(config)

    parent = graph.resolve(head) if head else graph.single_head()
    if head and parent is not None and graph.children[parent]:
        out.warn(f"{parent} already has children; this creates a new branch (a second head).")
    if rev_id and rev_id in graph:
        raise RevisionConflictError(f"Revision id {rev_id!r} already exists.")

    if autogenerate:
        _autogenerate(out, config, graph, message, parent, rev_id, renames or [])
        return

    new_id, path = write_revision(
        config.versions_dir,
        message=message,
        down_revision=parent,
        snapshot_hash=snapshot_hash(config.snapshot_path),
        rev_id=rev_id,
    )
    shown = relpath(path, config)

    def render(con: Console) -> None:
        con.print(f"[green]Created revision[/green] [bold]{new_id}[/bold] → {shown}")
        con.print(f"  revises: {parent or '<base>'}")

    out.result({"revision": new_id, "down_revision": parent, "path": shown}, render)


def _autogenerate(
    out: Output,
    config: LoadedConfig,
    graph: RevisionGraph,
    message: str,
    parent: str | None,
    rev_id: str | None,
    renames: list[str],
) -> None:
    from mongomig.cli.commands._schema import compute
    from mongomig.cli.commands.diff import render_diff
    from mongomig.generators.render import generate
    from mongomig.schema.snapshot import content_hash, write_snapshot

    state: SchemaState = compute(config, graph, renames)
    diff = state.diff

    if not diff.has_changes:

        def render_none(con: Console) -> None:
            for warning in diff.warnings:
                con.print(f"[yellow]warning:[/yellow] {warning}")
            con.print("[green]No schema changes detected; no revision generated.[/green]")

        out.result({"revision": None, "changes": []}, render_none)
        return

    generated = generate(diff)
    notes = ["Autogenerated from model changes. Review before running.", "", "Changes:"]
    notes += [f"  {line}" for line in generated.summary]
    if generated.review:
        notes += ["", "Needs review (see TODO(review) comments):"]
        notes += [f"  - {line}" for line in generated.review]

    snapshot_data = state.new_snapshot.to_dict()
    new_id, path = write_revision(
        config.versions_dir,
        message=message,
        down_revision=parent,
        snapshot_hash=content_hash(snapshot_data),
        rev_id=rev_id,
        upgrade_body=generated.upgrade_body,
        downgrade_body=generated.downgrade_body,
        notes="\n".join(notes),
    )
    # Only after the revision file exists: the snapshot now describes the models.
    write_snapshot(config.snapshot_path, snapshot_data)
    shown = relpath(path, config)

    def render(con: Console) -> None:
        render_diff(con, diff, title="Detected")
        con.print(f"[green]Generated[/green] [bold]{new_id}[/bold] → {shown}")
        con.print("  updated: migrations/schema_snapshot.json")
        if generated.review:
            con.print(
                f"[magenta]{len(generated.review)} item(s) need review[/magenta] "
                "(search the file for TODO(review))."
            )
        con.print("Review the file, then run `mongomig upgrade`.")

    out.result(
        {
            "revision": new_id,
            "down_revision": parent,
            "path": shown,
            "review": generated.review,
            **diff.to_dict(),
        },
        render,
    )
