"""initial schema

Revision: 5bb926ed2fb2
Revises: <base>
Created: 2026-09-25 12:54:59 UTC

Autogenerated from model changes. Review before running.

Changes:
  orders: + collection orders  [SAFE]
  orders: + index user_email_1_created_at_-1 (user_email ↑, created_at ↓)  [SAFE]
  users: + collection users  [SAFE]
  users: + index users_email_unique (email ↑, unique)  [WARNING]
  users: + validator (level=moderate)  [WARNING]
"""

revision = "5bb926ed2fb2"
down_revision = None
branch_labels = None
depends_on = None
reversible = True
snapshot_hash = "sha256:7ebeb558653a58f0fab7d352d71000a8d10f6b4f1586f819682e0844d2d0e675"
mongomig_format = 1


def upgrade(ctx):
    ctx.ops.create_collection("orders")

    ctx.ops.create_collection("users")

    ctx.ops.create_index(
        "orders",
        [("user_email", 1), ("created_at", -1)],
        name="user_email_1_created_at_-1",
    )

    ctx.ops.create_index("users", "email", name="users_email_unique", unique=True)

    ctx.ops.set_validator(
        "users",
        {
            "$jsonSchema": {
                "bsonType": "object",
                "required": ["_id", "name", "email", "status", "profile", "created_at"],
                "properties": {
                    "_id": {"bsonType": "objectId"},
                    "name": {"bsonType": "string"},
                    "email": {"bsonType": "string"},
                    "status": {"bsonType": "string"},
                    "profile": {
                        "bsonType": "object",
                        "required": ["bio", "email_verified"],
                        "properties": {
                            "bio": {"bsonType": ["string", "null"]},
                            "email_verified": {"bsonType": "bool"},
                        },
                    },
                    "created_at": {"bsonType": "date"},
                },
            },
        },
        level="moderate",
        action="error",
    )


def downgrade(ctx):
    ctx.ops.remove_validator("users")

    ctx.ops.drop_index("users", "users_email_unique")

    ctx.ops.drop_index("orders", "user_email_1_created_at_-1")

    # users was created by this revision. Dropping it deletes all its data:
    # ctx.ops.drop_collection("users")

    # orders was created by this revision. Dropping it deletes all its data:
    # ctx.ops.drop_collection("orders")
