"""add role and phone

Revision: cba0b1e69f99
Revises: 5bb926ed2fb2
Created: 2026-09-25 12:56:00 UTC

Autogenerated from model changes. Review before running.

Changes:
  users: + role: string = 'member'  [REQUIRES_DATA_MIGRATION]
  users: + phone: string | null = None  [SAFE]
  users: + index role_1 (role ↑)  [SAFE]
  users: ~ validator (level=moderate)  [WARNING]
"""

revision = "cba0b1e69f99"
down_revision = "5bb926ed2fb2"
branch_labels = None
depends_on = None
reversible = True
snapshot_hash = "sha256:12e64ffa6c679f5f25d1a8f4fbb21376d5455be09448d8aa67f6426342c0824b"
mongomig_format = 1


def upgrade(ctx):
    # role: new required field; backfill existing documents
    ctx.ops.backfill("users", {"role": {"$exists": False}}, {"$set": {"role": "member"}})

    ctx.ops.create_index("users", "role", name="role_1")

    ctx.ops.set_validator(
        "users",
        {
            "$jsonSchema": {
                "bsonType": "object",
                "required": [
                    "_id",
                    "name",
                    "email",
                    "status",
                    "role",
                    "phone",
                    "profile",
                    "created_at",
                ],
                "properties": {
                    "_id": {"bsonType": "objectId"},
                    "name": {"bsonType": "string"},
                    "email": {"bsonType": "string"},
                    "status": {"bsonType": "string"},
                    "role": {"bsonType": "string"},
                    "phone": {"bsonType": ["string", "null"]},
                    "profile": {
                        "bsonType": "object",
                        "required": ["bio", "email_verified"],
                        "properties": {
                            "bio": {"bsonType": ["string", "null"]},
                            "email_verified": {"bsonType": "bool"},
                        },
                    },
                    "created_at": {"bsonType": "date"},
                },
            },
        },
        level="moderate",
        action="error",
    )


def downgrade(ctx):
    ctx.ops.set_validator(
        "users",
        {
            "$jsonSchema": {
                "bsonType": "object",
                "properties": {
                    "_id": {"bsonType": "objectId"},
                    "created_at": {"bsonType": "date"},
                    "email": {"bsonType": "string"},
                    "name": {"bsonType": "string"},
                    "profile": {
                        "bsonType": "object",
                        "properties": {
                            "bio": {"bsonType": ["string", "null"]},
                            "email_verified": {"bsonType": "bool"},
                        },
                        "required": ["bio", "email_verified"],
                    },
                    "status": {"bsonType": "string"},
                },
                "required": ["_id", "name", "email", "status", "profile", "created_at"],
            },
        },
        level="moderate",
        action="error",
    )

    ctx.ops.drop_index("users", "role_1")

    ctx.ops.unset_field("users", "role")
