"""orders

Revision: 7b3c14f5cbef
Revises: <base>
Created: 2026-10-03 18:50:54 UTC

Autogenerated from model changes. Review before running.

Changes:
  orders: + collection orders  [SAFE]
  orders: + index customer.last_1_customer.first_1 (customer.last ↑, customer.first ↑)  [SAFE]
"""

revision = "7b3c14f5cbef"
down_revision = None
branch_labels = None
depends_on = None
reversible = True
snapshot_hash = "sha256:b1caa29404c7019e1baeb1a3d90ae141537bcd65196bc5c4e58fdba667ace3e2"
mongomig_format = 1


def upgrade(ctx):
    ctx.ops.create_collection("orders")

    ctx.ops.create_index(
        "orders",
        [("customer.last", 1), ("customer.first", 1)],
        name="customer.last_1_customer.first_1",
    )


def downgrade(ctx):
    ctx.ops.drop_index("orders", "customer.last_1_customer.first_1")

    # orders was created by this revision. Dropping it deletes all its data:
    # ctx.ops.drop_collection("orders")
