"""initial catalog

Revision: 9feb474b4d28
Revises: <base>
Created: 2026-09-25 12:56:01 UTC

Autogenerated from model changes. Review before running.

Changes:
  products: + collection products  [SAFE]
  products: + index price_recent (price ↑, created_at ↓)  [SAFE]
  products: + index sku_1 (sku ↑, unique)  [WARNING]
  products: + index title_1 (title ↑)  [SAFE]
  products: + index title_text (title text)  [SAFE]
  reviews: + collection reviews  [SAFE]
  reviews: + index product_sku_1 (product_sku ↑)  [SAFE]
"""

revision = "9feb474b4d28"
down_revision = None
branch_labels = None
depends_on = None
reversible = True
snapshot_hash = "sha256:844b3aaab7c2f3d91bbaf41f142659fef33fb019e773a17d566e1389a3b34d4b"
mongomig_format = 1


def upgrade(ctx):
    ctx.ops.create_collection("products")

    ctx.ops.create_collection("reviews")

    ctx.ops.create_index("products", [("price", 1), ("created_at", -1)], name="price_recent")

    ctx.ops.create_index("products", "sku", name="sku_1", unique=True)

    ctx.ops.create_index("products", "title", name="title_1")

    ctx.ops.create_index("products", [("title", "text")], name="title_text")

    ctx.ops.create_index("reviews", "product_sku", name="product_sku_1")


def downgrade(ctx):
    ctx.ops.drop_index("reviews", "product_sku_1")

    ctx.ops.drop_index("products", "title_text")

    ctx.ops.drop_index("products", "title_1")

    ctx.ops.drop_index("products", "sku_1")

    ctx.ops.drop_index("products", "price_recent")

    # reviews was created by this revision. Dropping it deletes all its data:
    # ctx.ops.drop_collection("reviews")

    # products was created by this revision. Dropping it deletes all its data:
    # ctx.ops.drop_collection("products")
